### PR TITLE
fix problem with defaultCountry number concatenation

### PR DESCRIPTION
**Pull request by lunaticusgreen**
https://github.com/bl00mber/react-phone-input-2/issues/100

### CODE REVIEW

**Comment by dmitriy219** [comment]
Hello, thanks for the fix!
I kindly ask @bl00mber to review and merge this PR as soon as possible, as this bug is very visible for the users of our website and breaks user experience for them.

**Comment by jonchaney** [comment]
Please review and merge this code in @bl00mber. bug is a big issue.

**Comment by renatohlf** [comment]
Thanks for the fix!! Please, review and merge this PR.

**Comment by jonchaney** [comment]
i reverted to version "2.8.0" and it's working for me as this fix is too critical to wait for the PR to be merged.

**Comment by lunaticusgreen** [comment]
@jonchaney I created a package in npm react-phone-input-new, with only this fix, to use it in my project, you can switch to it temporarily, and switch back when it will be fixed in this package

**Comment by lunaticusgreen** [comment]
Did it because SSR fix was strongly needed

**Comment by jonchaney** [comment]
@lunaticusgreen ya, I was thinking about doing that too, but if you already did it I will gladly use yours. Thanks!

**Comment by bl00mber** [comment]
You can use 
`"react-phone-input-2": "git+https://github.com/lunaticusgreen/react-phone-input-2.git#9a2baba8fc9b20eecfc0c3086b6d3e76056d9ca8",`

**Pull request merged**
