### PR TITLE
Resolve issue 118

### PR DESCRIPTION
**Pull request by khippert5**
Limits the country return in guessSelectedCountry() to only those without areaCode if disableAreaCodes=true. Not doing this causes an issue with input freeze if countryCodeEditable=false and autoFormat=false.

### CODE REVIEW

**Comment by khippert5** [comment]
I am looking to see if I can get this merged. I have currently created a new npm package with this fix in place. I would like to remove this new package and continue to use this so that the react-intl-phone3 doesn't need to be maintained.

**Comment by khippert5** [comment]
Have updated with master for available merge

**Comment by bl00mber** [comment]
This not solves input freezing when the same props used without disableAreaCodes. Someone may stop receiving area codes in his app because of this change.

**Comment by khippert5** [comment]
Understandable if you do not want to use this. This update allowed me to use "dial code" as its intended tracking/use case; for area code is not considered part of the dial code.
A great use case for area code would be a "type-a-head" feature to allow the user to select the dial code. :) 
I like the content freeze on dial code. It forces the user to select from the flag drop down. However; area code really shouldn't be used as a content freeze. The area code should always be allowed editable by the user for type-o updates. If the user inputs the wrong area code by mistake and it is in freeze, they can not go back and edit this without a form refresh. You run the risk of losing the user because of this. The ideal user flow should always allow for area code to be editable by the user.

**Comment by bl00mber** [comment]
I am talking about the same, yes I see this bug, but this PR do not solving the similar freezing bug with disableAreaCodes=false and it prevents area code from passing with the data object.

**Comment by bl00mber** [comment]
Closed in favor of my fix which works with disableAreaCodes={false}, does not breaks filter of countries and highlight in the dropdown.

**Pull request closed without merging**
