### PR TITLE
Screenreader/keyboard accessibility attributes, styles

### PR DESCRIPTION
**Pull request by sackeyjason**
Here are the changes I suggested [here](https://github.com/bl00mber/react-phone-input-2/issues/250):

- Moving the button ARIA role and button behaviour down to the selected-flag div
- Additional ARIA attributes
- CSS changes, to keep everything looking the same
- added country selector focus states on the material and bootstrap themes (based on the styling for their respective input fields)

### CODE REVIEW

**Comment by hughriegelwt** [comment]
My team is currently trying to get a build out and accessibility issues are stopping us. Thank you so much 😊 great change.

**Comment by bl00mber** [comment]
You should allow me to edit the PR! The box is in the right column

**Comment by sackeyjason** [comment]
I'm afraid I don't see a checkbox in the right column. I just tried to give you write access to it in the settings.

**Comment by bl00mber** [comment]
Screenshot from 2020-06-26

**Comment by sackeyjason** [comment]
I don't have the checkbox on my page. I think it's because I forked into an organisation project. I'm happy to make a new normal fork and resubit the PR.

**Pull request closed without merging**
