### PR TITLE
Implemented input ref fix from https://github.com/bl00mber/react-phon…

### PR DESCRIPTION
**Pull request by DylanCulfogienis**
Implement fix suggested by @ntower https://github.com/bl00mber/react-phone-input-2/issues/187#issuecomment-734925729

### CODE REVIEW

**Comment by ntower** [comment]
Don't forget to remove the old ref code, on line 953
```
ref={el => this.numberInputRef = el}
```

**Comment by DylanCulfogienis** [comment]
Good catch, fixed.

**Comment by isener** [comment]
This should have been merged already. Hello `react-hook-form` ers

**Comment by jacobgranberry** [comment]
@bl00mber Hi there, is it possible to look at this and determine if you can merge it?  Will help hooking up your phone input to Formik/react-hook-form

**Comment by Stekmo** [comment]
@bl00mber Also really in need of this.

**Pull request merged**
