### PR TITLE
Fix to enable autocomplete or paste when countryCodeEditable is false

### PR DESCRIPTION
**Pull request by jonathancalb**
Fix for https://github.com/bl00mber/react-phone-input-2/issues/328

### CODE REVIEW

**Review by CapleaIonut-Alexandru — APPROVED** [review]

**Review by ionutmiftode — APPROVED** [review]

**Review by mimi26 — APPROVED** [review]

**Comment by GarrettJMU** [comment]
@CapleaIonut-Alexandru @ionutmiftode @mimi26 @bl00mber any chance this will get merged soon? Pretty decent pain point.

**Comment by GarrettJMU** [comment]
@jonathancalb I'd also like to see what settings you used to get this to work. It's still not working when pointing at this commit using:
```
countryCodeEditable={false}
autocompleteSearch={true}
```

**Comment by jonathancalb** [comment]
@GarrettJMU added in the demo the autocomplete case. You can test it there and see the settings I used in this PR. @bl00mber can we move this forward? We are using the library in a project and considering forking it because there is no response here. Thanks!

**Comment by GarrettJMU** [comment]
@jonathancalb so when I pointed to your project I'm still not getting Autocomplete working. I also tried cloning the repo and not getting it there either. Is there anything else I should be using/have? Would it be helpful if I included a screenshare?

**Comment by jonathancalb** [comment]
@GarrettJMU do you have any addresses saved in your browser? It will get the mobile number you got saved there. If not it will not find anything to autocomplete.

**Comment by jonathancalb** [comment]
@bl00mber closing this PR since we are forced to fork to get this fixed. A shame that this library is not maintained.

**Comment by bl00mber** [comment]
Seems I cannot merge this since there are credentials hijacking.

**Comment by bl00mber** [comment]
This is probably not working, can anyone explain what the changes here doing and how to test this?

**Pull request closed without merging**
