### PR TITLE
Support React 18 and add GitHub action for building and testing

### PR DESCRIPTION
**Pull request by razshlomo**
Hey,

My first contribution to this repo :-)
Addresses https://github.com/bl00mber/react-phone-input-2/issues/520

Thanks!

### CODE REVIEW

**Comment by robert-sperse** [comment]
@bl00mber can you please merge and publish a new version. This is straight forward, not sure what else you need

**Comment by bl00mber** [comment]
I don't need "GitHub action"

**Comment by robert-sperse** [comment]
I was referring to react18, which has been out for a while and still the
package.json restricts to 17 even though 18 works.

If you don't have plans to maintain this project please archive it so
others know this isn't going to be maintained.

**Comment by bl00mber** [comment]
@robert-sperse are you alternatively challenged? The new version is published. Moreover, if you want to use react 18, you as well may tweak npm configuration file in your project. I advise you to stop giving me orders what to do, or you will be blocked.

**Pull request closed without merging**
