### PR TITLE
fix #250 accessibility aria attributes and styling

### LINKED ISSUE #250: Country code selector screenreader accessibility
I've been working on this, and intend to put forward a pull request.

As it stands, you can't navigate the country code dropdown list as a blind screenreader user. The list items are all smooshed together because of the role="button" attribute on the ancestor.

So I suggest:

- move that role attribute down to the 'selected-flag' div
- add extra attributes to make it function more like a native select element:
  - add 'listbox' and 'option' roles, plus the `aria-selected="true"` attribute
  - example here: https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html
  - but don't worry about `aria-activedescendant` (trickier to implement and, in my testing, unnecessary)

### PR DESCRIPTION
**Pull request by sackeyjason**
Redo of [this PR](https://github.com/bl00mber/react-phone-input-2/pull/251) to fix issue #250.

### CODE REVIEW

**Comment by bl00mber** [comment]
Check this out, if this works I'll merge it. The outline should be disabled on default views.

**Comment by sackeyjason** [comment]
Looks good. The CSS changes ensured that the button focus effect still worked as before, and removed some repeated styles.

Also, for the Material and Boostrap themes, it added outlines to the buttons in the style of the focused form fields. But they were not needed for this issue, and we can use CSS outside the library for this now.

**Comment by sackeyjason** [comment]
Here are screenshots of the focus outlines.

Screenshot 2020-06-26 at 23 32 29
Screenshot 2020-06-26 at 23 32 37

**Comment by bl00mber** [comment]
The bootstrap version looks good. I'll keep that.

**Pull request merged**
