### PR TITLE
modernize

### PR DESCRIPTION
**Pull request by jnsdls**
- upgraded dependencies
- updated webpack to v4
- reduced build size (215 KB -> 98.9 KB) ((GZIP: ~ 107KB -> ~44KB))
- no more warnings in <StrictMode>
- same API & data
- used yarn to generate a lockfile

FIXES:
#63 
#44 (partially, by including used functions directly via lodash-es)

### CODE REVIEW

**Comment by jnsdls** [comment]
@bl00mber please have a look, if there's something you'd like me to change I'm happy to make adjustments

**Comment by jnsdls** [comment]
@bl00mber hope you made it into 2019 okay, any chance u could look at this? :)

**Comment by bl00mber** [comment]
Hello! Please discard following files from your PR: `yarn.lock`, `src/global.js`, `src/flags.png`, `src/demo.js` (all changed content of `demo.js`, if new necessary customization examples was not added), `src/country_data.js` (indentation and style changes in `country_data.js`) and all stylish changes from `src/index.js`. Before already was an PR with style changes that have been discarded, probably I will add to README.md that style edits are not accepted.

**Comment by bl00mber** [comment]
Are you planning to edit your PR? I'll commit these changes myself within next few weeks if not.

**Comment by jnsdls** [comment]
@bl00mber I’ll see if I have time to edit it. Don’t have much time this week. If you have the time to pull out the pieces you want obviously feel free to.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bl00mber** [comment]
I'm actually working over it and probably will remove `lodash` so it's not necessary anymore.

**Pull request closed without merging**
