### PR TITLE
Better keyboard support and fixing DOM structure

### PR DESCRIPTION
**Pull request by Rafi993**
1. Adding tab index to list item and key board event
2. Moving search input out of ul

### CODE REVIEW

**Comment by bl00mber** [comment]
Don't understood why the search fields needs to be placed out of the ul (the tag in this PR is also broken). onClick, onKeyPress do the same actions, why use both? Tab usage is a good idea, will probably add it. Anyways, thanks for the PR!

**Comment by Rafi993** [comment]
onKeypress gets triggered for keyboard events while onClick for mouse clicks

**Comment by Rafi993** [comment]
when you add tabIndex="0" to make element element focusable by keyboard you do add onKeyPress so that user can trigger it using enter and onClick for mouse clicks. This is not required for interactive elements like button. But when you make non-interactive elements like div interactive you may need to add it.

**Comment by bl00mber** [comment]
There is already onKeyPress event for dropdown items.

**Pull request closed without merging**
